/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.orderevent.dto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderStatus {
  UNKNOWN, CREATED, CONFIRMED, SHIPPED, DELIVERED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderStatus\",\"namespace\":\"com.orderevent.dto\",\"symbols\":[\"UNKNOWN\",\"CREATED\",\"CONFIRMED\",\"SHIPPED\",\"DELIVERED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
